[capture]
file = "capture_20260409_090615_test_tone_generator_sine_wave.pcapng"
format = "pcapng"

[description]
feature = "test tone generator sine wave"
notes = "start aplication; enable test tone generator sine wave; sweep throug frequencies: 20Hz ... 20kHz ... 20Hz ... 25Hz; restart application; 20Hz is the default freqency; the software alloes to choose from a list of freqencies, all of these frequencies have been selected in this capture"

[analysis]
packet_count = 574
out_packets = 287
in_packets = 287
duration_seconds = 48.75
opcodes_seen = [
    "0x01",
    "0x10",
    "0x12",
    "0x13",
    "0x14",
    "0x22",
    "0x24",
    "0x27",
    "0x29",
    "0x2c",
    "0x39",
    "0x40",
]
has_unknown_opcodes = false
has_checksum_errors = false
last_analyzed = "2026-04-15T13:18:26"

[analysis.opcode_counts]
0x40 = 270
0x29 = 120
0x01 = 64
0x39 = 62
0x27 = 18
0x24 = 18
0x10 = 4
0x13 = 4
0x2c = 4
0x22 = 4
0x14 = 4
0x12 = 2
