[capture]
file = "capture_20260405_171839_output_channel_xover_highpass_bypass.pcapng"
format = "pcapng"
created = "2026-04-05T17:19:05"
source_machine = "windows"
interface = "\\\\.\\USBPcap1"
device_address = 13

[description]
feature = "output channel xover highpass bypass"
notes = "captured output channel 3 xover high pass bypass; change bypassed to not bypassed to bypassed to not bypassed (bypass enabled is default); restartet application"
