ref_level24 = 20477.4
ref_level = 79.99

[[points]]
dbu = 6.0
channel = "InC"
channel_index = 2
mean_uint16 = 161.4
min_uint16 = 160
max_uint16 = 163
samples = 20
timestamp = "2026-09-20T13:13:05"

[[points]]
dbu = 0.0
channel = "InC"
channel_index = 2
mean_uint16 = 78.15
min_uint16 = 77
max_uint16 = 79
samples = 20
timestamp = "2026-09-20T13:08:41"
